name = "wb-widget-api"
main = "api/worker.js"
compatibility_date = "2024-09-01"

# KV binding for tokens/state
[[kv_namespaces]]
binding = "KV"
id = "YOUR_KV_NAMESPACE_ID" # set after creating KV in Cloudflare dashboard (or via wrangler)

# If you also want to host the widget with Cloudflare Pages, keep that separate.
